# ---------------------------------------------------------------------------
# importTif.py
# Created on: 2012-04-18 10:06:29.00000
#   (generated by ArcGIS/ModelBuilder)
# Description:
# ---------------------------------------------------------------------------

# Import arcpy module
import sys, arcpy, time
from arcpy.sa import *

def main(rootDir, rasterName, outputGdb, outputPrefix):
    # Check out the ArcGIS Spatial Analyst extension license
    arcpy.CheckOutExtension("Spatial")
    heightVars = ["max", "_mn", "p95", "p80", "p75"]

    ##try:
    ##    # Process: Raster Calculator
    ##    arcpy.gp.RasterCalculator_sa("Con(\"" + rootDir + rasterName + ".tif\" > -9999, \"" + rootDir + rasterName + ".tif\")", rootDir + rasterName)
    ##    print "\n" + arcpy.GetMessages()
    ##
    ##except:
    ##    print arcpy.GetMessages()

    # Process conditiional statement. Raster function necessary if not using whereClause
    if rasterName[-3:] in heightVars:
        outRaster = Con((Raster(rootDir + rasterName + ".tif") > -9999), Con((Raster(rootDir + rasterName + ".tif") < 100), (rootDir + rasterName + ".tif")))
    else:
        outRaster = Con((Raster(rootDir + rasterName + ".tif") > -9999), (rootDir + rasterName + ".tif"))
    # outRaster = Con(rootDir + rasterName + ".tif", rootDir + rasterName + ".tif", "", whereClause)

    time.sleep(20)
    outRaster.save(outputGdb + "\\" + outputPrefix + rasterName[-3:])

    # os.system("del " + rootDir + rasterName + ".tif")

    print "\nimportTif Done.\n\n"

if __name__ == '__main__':
        # Test for correct number of arguments
    if len(sys.argv) != 5:
        print "Usage: importTif <rootDir w/trailing \\> <rasterName> <outputGdb> <outputPrefix>"
        sys.exit(1)

    try:
        main(sys.argv[1], sys.argv[2], sys.argv[3], sys.argv[4])

    except Exception, e:
        print "\n\n" + sys.argv[2] + ": " + e.args[0]

    except:
        print "unhandled Error!!"
